### ISSUE TITLE
Speed/offline improvements

### ISSUE THREAD

**Issue by feross** [feross/available#1]
From https://twitter.com/zeke/status/624301426244653056:

Use these packages:

- https://www.npmjs.com/package/all-the-package-names
- https://www.npmjs.com/package/an-array-of-english-words

**Comment by zeke** [comment]
:cake:

**Comment by feross** [comment]
Released as v1.1.0.

Couldn't use the array of all english words, because there are too many weird words. The current dictionary is ordered by popularity. I wish it was more than 10,000 words, but it'll do for now.

**Comment by zeke** [comment]
OFFLINE MODE

Nice.
