### ISSUE TITLE
Does not take into account the new rules

### ISSUE THREAD

**Issue by GrosSacASac** [feross/available#12]
https://blog.npmjs.org/post/168978377570/new-package-moniker-rules

**Comment by feross** [comment]
I can't think of an easy way to check this without actually registering the package. In most cases, this shouldn't be an issue anyway. If you find a way to check this, please send a PR.

**Comment by laggingreflex** [comment]
Wouldn't it'd be easy to do (at least for offline mode) by just checking the possibilities in [all-the-package-names](https://www.npmjs.com/package/all-the-package-names)? I could help with a PR if this approach is viable. 

In the meantime I created a package that does just that - [name-exists](https://github.com/laggingreflex/name-exists) (before I knew _this_ package existed)
